/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication12;

/**
 *
 * @author HP
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {
    
    private Connection conn;
    private PreparedStatement pstmt;
    private ResultSet rs;
    private DefaultTableModel model;
   

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        conn=connection.getConnection();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDPasien1 = new javax.swing.JLabel();
        lblIDPasien = new javax.swing.JLabel();
        lblIDDokter = new javax.swing.JLabel();
        lblIDOrder2 = new javax.swing.JLabel();
        txtIDTransaksi = new javax.swing.JTextField();
        txtIDPasien = new javax.swing.JTextField();
        txtIDDokter = new javax.swing.JTextField();
        txtNamaPasien = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        txtNamaDokter = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btncari = new javax.swing.JButton();
        txtPenyakit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblIDPasien1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDPasien1.setText("ID Kamar");

        lblIDPasien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDPasien.setText("ID Pasien");

        lblIDDokter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDDokter.setText("ID Dokter");

        lblIDOrder2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDOrder2.setText("Nama Pasien");

        txtIDTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTransaksiActionPerformed(evt);
            }
        });

        txtIDPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPasienActionPerformed(evt);
            }
        });

        txtIDDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDDokterActionPerformed(evt);
            }
        });

        txtNamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPasienActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label3.setText("Alamat");

        label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label2.setText("Nama Dokter");

        label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label4.setText("Penyakit");

        txtNamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDokterActionPerformed(evt);
            }
        });

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTambah.setText("Simpan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableData);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DATA PASIEN RAWAT INAP");

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        txtPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenyakitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIDPasien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIDPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblIDOrder2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblIDDokter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIDDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblIDPasien1)
                                        .addGap(56, 56, 56)
                                        .addComponent(txtIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2)
                                    .addComponent(label4)
                                    .addComponent(label3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIDPasien1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2)
                        .addComponent(txtNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDPasien)
                    .addComponent(txtIDPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDOrder2)
                    .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4)
                    .addComponent(txtPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDDokter)
                    .addComponent(txtIDDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnReset)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTransaksiActionPerformed

    private void txtIDPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPasienActionPerformed

    private void txtIDDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDDokterActionPerformed

    private void txtNamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPasienActionPerformed

    private void txtNamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDokterActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        addData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        addData();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtIDTransaksi.setText("");
            txtIDPasien.setText("");
            txtNamaPasien.setText("");
            txtIDDokter.setText("");
            txtNamaDokter.setText("");
            txtAlamat.setText("");
            txtCari.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_formWindowOpened

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        // TODO add your handling code here:
        txtIDTransaksi.setText(model.getValueAt(tableData.getSelectedRow(),0).toString());
        showDataForm();
    }//GEN-LAST:event_tableDataMouseClicked

    private void txtPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenyakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenyakitActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try{
            rs=pstmt.executeQuery("select * from transaction where "+"id_kamar like '%" +txtCari.getText()+"%' OR "+"nama_pasien like '%"+txtCari.getText()+"%'");
            
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("id_kamar");
            tbl.addColumn("id_pasien");
            tbl.addColumn("nama_pasien");
            tbl.addColumn("id_dokter");
            tbl.addColumn("nama_dokter");
            tbl.addColumn("alamat_pasien");
            tbl.addColumn("penyakit");
            
            tableData.setModel(tbl);
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("id_kamar"),
                    rs.getString("id_pasien"),
                    rs.getString("nama_pasien"),
                    rs.getString("id_dokter"),
                    rs.getString("nama_dokter"),
                    rs.getString("alamat_pasien"),
                    rs.getString("penyakit"),
                });
                tableData.setModel(tbl);
            }
            }catch (SQLException se){
                System.out.println(se);
               
                
            }
    
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
     private void showData(){
        Object [][] data=null;
        try{
            String myQuery = null;     
                myQuery="select * from transaction";     
            pstmt=conn.prepareStatement(myQuery);
            rs=pstmt.executeQuery();
            rs.last();//pointer ke record terakhir
            int jmlRec=rs.getRow();//nomor record= jumlah record dalam table
            data=new Object[jmlRec][7];
            rs.beforeFirst();//pointer sebelum ke record pertama
            int i=0;
            while(rs.next()){
                data[i][0] =rs.getString("id_kamar");
                data[i][1] =rs.getString("id_pasien");
                data[i][2] = rs.getString("nama_pasien");
                data[i][3] = rs.getString("id_dokter");
                data[i][4] = rs.getString("nama_dokter");
                data[i][5] = rs.getString("alamat_pasien");
                data[i][6] = rs.getString("penyakit");
                i++;
            }
        }
        catch(SQLException se){
            System.out.println(se);
        }
        String[] judul={"ID Kamar","ID Pasien","Nama Pasien","ID Dokter","Nama Dokter",
            "Alamat", "Penyakit"};
        model=new DefaultTableModel(data,judul);
        tableData.setModel(model);
    }
     
     private void showDataForm(){
        try{
            pstmt=conn.prepareStatement("select * from transaction where id_kamar=? ");
            pstmt.setString(1, txtIDTransaksi.getText());
            rs=pstmt.executeQuery();
            if(rs.next()){
                
                txtIDPasien.setText(rs.getString("id_pasien"));
                txtNamaPasien.setText(rs.getString("nama_pasien"));
                txtIDDokter.setText(rs.getString("id_dokter"));
                txtNamaDokter.setText(rs.getString("nama_dokter"));
                txtAlamat.setText(rs.getString("alamat_pasien"));
                txtPenyakit.setText(rs.getString("penyakit"));
                
            }
            else{
                txtIDPasien.setText("");
                txtNamaPasien.setText("");
                txtIDDokter.setText("");
                txtNamaDokter.setText("");
                txtAlamat.setText("");
                txtPenyakit.setText("");
            }
    }catch(SQLException se){
            System.out.println(se);
        }
    }
    
   private void addData(){
        try{
            pstmt=conn.prepareStatement("select * from transaction where id_kamar=?");
            pstmt.setString(1,txtIDTransaksi.getText());
            rs=pstmt.executeQuery();
            String myQuery;
            if (rs.next()) {
                myQuery="update transaction set id_pasien=?, nama_pasien=?, id_dokter=?"
                        + ", nama_dokter=?, alamat_pasien=?, penyakit=? where id_kamar=?";
                JOptionPane.showMessageDialog(null, "Data Berhasil Di-update!");
                pstmt=conn.prepareStatement(myQuery);   
                pstmt.setString(1,txtIDPasien.getText());
                pstmt.setString(2,txtNamaPasien.getText());
                pstmt.setString(3,txtIDDokter.getText()); 
                pstmt.setString(4,txtNamaDokter.getText());
                pstmt.setString(5,txtAlamat.getText()); 
                pstmt.setString(6,txtPenyakit.getText());
                pstmt.setString(7,txtIDTransaksi.getText());
                pstmt.executeUpdate();
            }
            else{
                myQuery="insert into transaction (id_kamar,id_pasien,nama_pasien,id_dokter"
                        + ",nama_dokter,alamat_pasien,penyakit) values (?,?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(null, "Data Berhasil Di-Simpan!");
                pstmt=conn.prepareStatement(myQuery);   
                pstmt.setString(1,txtIDTransaksi.getText());
                pstmt.setString(2,txtIDPasien.getText());
                pstmt.setString(3,txtNamaPasien.getText());
                pstmt.setString(4,txtIDDokter.getText()); 
                pstmt.setString(5,txtNamaDokter.getText());
                pstmt.setString(6,txtAlamat.getText()); 
                pstmt.setString(7,txtPenyakit.getText());
                pstmt.executeUpdate();
            }
            
            //pstmt.setString(5,txtID.getText());
            
            showData();
        }
        catch(SQLException se){
            System.out.println(se);
        }
    }
   
    private void deleteData(){
        try{
            pstmt=conn.prepareStatement("delete from transaction where id_kamar=?");
            pstmt.setString(1,txtIDTransaksi.getText());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di-Hapus");
            showData();
            
            txtIDTransaksi.setText("");
            txtIDPasien.setText("");
            txtNamaPasien.setText("");
            txtIDDokter.setText("");
            txtNamaDokter.setText("");
            txtAlamat.setText("");
            txtPenyakit.setText("");
            
        }
        catch(SQLException se){
            System.out.println(se);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btncari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel lblIDDokter;
    private javax.swing.JLabel lblIDOrder2;
    private javax.swing.JLabel lblIDPasien;
    private javax.swing.JLabel lblIDPasien1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIDDokter;
    private javax.swing.JTextField txtIDPasien;
    private javax.swing.JTextField txtIDTransaksi;
    private javax.swing.JTextField txtNamaDokter;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtPenyakit;
    // End of variables declaration//GEN-END:variables
}
